/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author davidrobinson
 */
import java.util.Calendar;
import java.util.List;
import java.util.Date;
import javax.swing.JList;
import javax.swing.JOptionPane;
public class GUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form GUIFrame
     */
    private BookingsQueries bookingsQueries;
    private WaitlistQueries waitlistQueries;
    private Customer customer;
    private Flight flight;
    private Day day;
    private int numberOfEntries = 0;

    private List<BookingEntry> results;
    //private List<Customer> results1;
    private List<String> results1;
    private List<Integer> numSeats;
    
    private List<String> fNameCDel;
    private List<java.sql.Date> dayCDel;
    
    private List<String> fNameCInfo;
    private List<java.sql.Date> dayCInfo;
    private List<String> fNameCInfoW;
    private List<java.sql.Date> dayCInfoW;
    
    private List<String> results2;
    private List<String> waitlistCurrent;
    private List<Date> results3;
    private List<String> results6;
    private List<String> results7;
    
    public GUIFrame() {
        super("FlightScheduler2DavidRobinsondpr5177");
        initComponents();
        bookingsQueries = new BookingsQueries();
        waitlistQueries = new WaitlistQueries();
        customer = new Customer();
        flight = new Flight();
        day = new Day();
        //results = bookingsQueries.getAllCustomers();
        results1 = customer.getAllCustomers();
        results2 = flight.getAllFlights();
        results3 = day.getAllDays();
        //CustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { results1.toString()}));
        CustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(results1.toArray()));
        
        DayComboBox.setModel(new javax.swing.DefaultComboBoxModel(results3.toArray()));
        DayStatusCombo.setModel(new javax.swing.DefaultComboBoxModel(results3.toArray()));
        CustomerCancelCombo.setModel(new javax.swing.DefaultComboBoxModel(results1.toArray()));
        CustomerInfoCombo.setModel(new javax.swing.DefaultComboBoxModel(results1.toArray()));
        //List<String> ls = new ArrayList<String>(); 
        //ComboBox.setModel(new DefaultComboBoxModel(ls.toArray()));
        FlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(results2.toArray()));
        FlightStatusCombo.setModel(new javax.swing.DefaultComboBoxModel(results2.toArray()));
        FlightRemoveCombo.setModel(new javax.swing.DefaultComboBoxModel(results2.toArray()));

        WaitlistDayCombo.setModel(new javax.swing.DefaultComboBoxModel(results3.toArray()));
        
        //java.sql.Date day1 = java.sql.Date.valueOf(DayStatusCombo.getSelectedItem().toString());
        //String y = FlightStatusCombo.getSelectedItem().toString();
        //results6 = bookingsQueries.getAllBookingEntriesByFlight(y,day1);
        //CustomersListComboBox.setModel(new javax.swing.DefaultComboBoxModel(results6.toArray())) ;
        
        //java.sql.Date day2 = java.sql.Date.valueOf(WaitlistDayCombo.getSelectedItem().toString());
       // results6 = waitlistQueries.getAllBookingEntriesByFlight(day2);
        //WaitlistStatusBox.setModel(new javax.swing.DefaultComboBoxModel(results6.toArray())) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        CustomerNameLabel = new javax.swing.JLabel();
        CustomerNameTextField = new javax.swing.JTextField();
        AddCustomerButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        DayComboBox = new javax.swing.JComboBox<>();
        FlightComboBox = new javax.swing.JComboBox<>();
        CustomerComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BookButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        FlightStatusCombo = new javax.swing.JComboBox<>();
        DayStatusCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FlightStatusButton = new javax.swing.JButton();
        CustomersListComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        WaitlistDayCombo = new javax.swing.JComboBox<>();
        ViewWaitlistButton = new javax.swing.JButton();
        WaitlistStatusBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        AddSeatButton = new javax.swing.JButton();
        SeatSpinner = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        AddFlightField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        CustomerCancelCombo = new javax.swing.JComboBox<>();
        CancelBookingButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        AddDayField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        AddDayButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CustomerInfoCombo = new javax.swing.JComboBox<>();
        CustomerInfoButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BookingFlightStatusTF = new javax.swing.JTextField();
        BookingDayStatusTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        WaitlistFlightStatusTF = new javax.swing.JTextField();
        WaitlistDayStatusTF = new javax.swing.JTextField();
        TestCombo = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        FlightRemoveCombo = new javax.swing.JComboBox<>();
        FlightRemoveButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Flight Scheduler");

        CustomerNameLabel.setText("Customer Name:");

        CustomerNameTextField.setColumns(15);

        AddCustomerButton.setText("Add");
        AddCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(CustomerNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(AddCustomerButton)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNameLabel)
                    .addComponent(CustomerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddCustomerButton)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Customer", jPanel2);

        DayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        FlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CustomerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Select a Customer:");

        jLabel3.setText("Select a Day:");

        jLabel4.setText("Select a Flight:");

        BookButton.setText("Book");
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(BookButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FlightComboBox, 0, 188, Short.MAX_VALUE)
                            .addComponent(DayComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustomerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(BookButton)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Booking", jPanel3);

        FlightStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DayStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Select Flight:");

        jLabel6.setText("Select Day:");

        FlightStatusButton.setText("View Flight Status");
        FlightStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightStatusButtonActionPerformed(evt);
            }
        });

        CustomersListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Customers:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(FlightStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel6))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(FlightStatusButton)
                                .addGap(19, 19, 19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DayStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel14)
                        .addGap(47, 47, 47)
                        .addComponent(CustomersListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DayStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FlightStatusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomersListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Flight Status", jPanel4);

        jLabel8.setText("Select Day:");

        WaitlistDayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ViewWaitlistButton.setText("View Waitlist");
        ViewWaitlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewWaitlistButtonActionPerformed(evt);
            }
        });

        WaitlistStatusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        WaitlistStatusBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaitlistStatusBoxActionPerformed(evt);
            }
        });

        jLabel15.setText("Customers:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WaitlistDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(ViewWaitlistButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(53, 53, 53)
                .addComponent(WaitlistStatusBox, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(WaitlistDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewWaitlistButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WaitlistStatusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Waitlist Status", jPanel5);

        jLabel7.setText("Seat Amount:");

        AddSeatButton.setText("Add Flight");
        AddSeatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSeatButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Flight Name:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddFlightField, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(SeatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(AddSeatButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SeatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(AddFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(AddSeatButton)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Flight", jPanel6);

        jLabel9.setText("Select a Customer:");

        CustomerCancelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CancelBookingButton.setText("Cancel Booking");
        CancelBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30)
                        .addComponent(CustomerCancelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(CancelBookingButton)))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CustomerCancelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(CancelBookingButton)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancel Booking", jPanel7);

        jLabel11.setText("Enter Date:");

        jLabel12.setText("Date should be added in the format \"yyyy-MM-dd\"");

        AddDayButton.setText("Add Day");
        AddDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(AddDayButton)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddDayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddDayButton)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Day", jPanel8);

        jLabel13.setText("Select Customer:");

        CustomerInfoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CustomerInfoButton.setText("View Status");
        CustomerInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerInfoButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Flight:");

        jLabel17.setText("Day:");

        jLabel18.setText("Booking");

        jLabel19.setText("Waitlist");

        jLabel20.setText("Flight:");

        jLabel21.setText("Day:");

        TestCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BookingFlightStatusTF, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(BookingDayStatusTF))))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaitlistDayStatusTF, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(WaitlistFlightStatusTF))
                        .addGap(115, 115, 115))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(CustomerInfoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(210, 210, 210))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(CustomerInfoButton))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(TestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CustomerInfoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(CustomerInfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(BookingFlightStatusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(WaitlistFlightStatusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingDayStatusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21)
                    .addComponent(WaitlistDayStatusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(TestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer Status", jPanel9);

        jLabel22.setText("Select Flight to Remove:");

        FlightRemoveCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        FlightRemoveButton.setText("Remove");
        FlightRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel22)
                        .addGap(33, 33, 33)
                        .addComponent(FlightRemoveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(FlightRemoveButton)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(FlightRemoveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FlightRemoveButton)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Drop Flight", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(241, 241, 241))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
///Add customer Button action even listener. this is where you get customers name, pass to classes, display somethign for user
    private void AddCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerButtonActionPerformed
        // TODO add your handling code here:
        int result4 = customer.addCustomer(CustomerNameTextField.getText());
        if(result4 == 1)
            JOptionPane.showMessageDialog(this,"Customer added!","Person added", JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Customer not added","Error", JOptionPane.PLAIN_MESSAGE);
        results1 = customer.getAllCustomers();
        CustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(results1.toArray()));
        CustomerCancelCombo.setModel(new javax.swing.DefaultComboBoxModel(results1.toArray()));
        CustomerInfoCombo.setModel(new javax.swing.DefaultComboBoxModel(results1.toArray()));

    }//GEN-LAST:event_AddCustomerButtonActionPerformed
///Customer Combo box to display customers to choose from.
    private void CustomerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CustomerComboBoxActionPerformed
//Booking Button action listener to book a customer
    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButtonActionPerformed
        // TODO add your handling code here:
        //results1 = customer.getAllCustomers();
        //CustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(results1.toArray()));
        flight = new Flight();
        java.sql.Date day1 = java.sql.Date.valueOf(DayComboBox.getSelectedItem().toString());
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        //This is the selcted customers name
        String x = CustomerComboBox.getSelectedItem().toString();
        //this is the selected flights name
        String y = FlightComboBox.getSelectedItem().toString();
        //Should not need the z here 
        //String z = FlightStatusCombo.getSelectedItem().toString();
        //java.sql.Date day1 = java.sql.Date.valueOf(DayStatusCombo.getSelectedItem().toString());
        //result7 should be the number of cutomers on the flight thus far
        
        results7 = bookingsQueries.flightChecker(y,day1);
        int seatsused;
        seatsused = results7.size();
        //int for number of seats on the specified flight
        numSeats = flight.FlightSeats(y);
        //TestCombo.setModel(new javax.swing.DefaultComboBoxModel(numSeats.toArray()));
        
        Integer value = numSeats.get(0);
        int result5 = 0;
        int result8 = 0;
        if(seatsused < value){
            result5 = bookingsQueries.addBooking(x,y,
                day1,currentTimestamp);
        }
        
        else{
            result8 = waitlistQueries.addBooking(x,y, day1, currentTimestamp);
        }
        if(result5 == 1)
            JOptionPane.showMessageDialog(this,"Customer successfully booked on flight","Customer Booked!", JOptionPane.PLAIN_MESSAGE);
        else
            if(result8 == 1)
                JOptionPane.showMessageDialog(this,"Customer has been added to the waitlist","Customer Waitlisted!", JOptionPane.PLAIN_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, "Booking not added","Error", JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_BookButtonActionPerformed
//Flight status button to display customers booked on the flight
    private void FlightStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightStatusButtonActionPerformed
        // TODO add your handling code here:
        bookingsQueries = new BookingsQueries();
        String y = FlightStatusCombo.getSelectedItem().toString();
        java.sql.Date day1 = java.sql.Date.valueOf(DayStatusCombo.getSelectedItem().toString());
        results6 = bookingsQueries.getAllBookingEntriesByFlight(y,day1);
        CustomersListComboBox.setModel(new javax.swing.DefaultComboBoxModel(results6.toArray())) ;
    }//GEN-LAST:event_FlightStatusButtonActionPerformed

    private void WaitlistStatusBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaitlistStatusBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_WaitlistStatusBoxActionPerformed

    private void ViewWaitlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewWaitlistButtonActionPerformed
        // TODO add your handling code here:
        waitlistQueries = new WaitlistQueries();
        java.sql.Date day1 = java.sql.Date.valueOf(WaitlistDayCombo.getSelectedItem().toString());
        results6 = waitlistQueries.getAllBookingEntriesByFlight(day1);
        WaitlistStatusBox.setModel(new javax.swing.DefaultComboBoxModel(results6.toArray())) ;
    }//GEN-LAST:event_ViewWaitlistButtonActionPerformed
//Button for adding the seats
    private void AddSeatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSeatButtonActionPerformed
        // TODO add your handling code here:
        Integer myint = (Integer) SeatSpinner.getValue();
        
        results3 = day.getAllDays();
        String y = AddFlightField.getText();
        int result9 = flight.addFlightSeat(y,myint);
        if(result9 == 1)
            JOptionPane.showMessageDialog(this,"Flight Added!","Flight added", JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Flight not added","Error", JOptionPane.PLAIN_MESSAGE);
        results2 = flight.getAllFlights();
        FlightStatusCombo.setModel(new javax.swing.DefaultComboBoxModel(results2.toArray()));
        FlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(results2.toArray()));
        FlightRemoveCombo.setModel(new javax.swing.DefaultComboBoxModel(results2.toArray()));

    }//GEN-LAST:event_AddSeatButtonActionPerformed

    private void CancelBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBookingButtonActionPerformed
        // TODO add your handling code here:
        String x = CustomerComboBox.getSelectedItem().toString();

        fNameCDel = bookingsQueries.getBookingFlight(x);
        dayCDel = bookingsQueries.getBookingDate(x);
        //String a = fNameCDel.get(0);        
        //java.sql.Date b = dayCDel.get(0);
        //Gets the waitlist for the specific flight
        //waitlistCurrent = waitlistQueries.checkAllBookingEntriesByFlight(a,b);
        //java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        //int result5 = 0;
        int result4 = bookingsQueries.cancelBooking(x);
        if(result4 == 1){
            JOptionPane.showMessageDialog(this,"Booking removed!","Booking Removed", JOptionPane.PLAIN_MESSAGE);
          //  if(waitlistCurrent.size() != 0)
           //     result5 = bookingsQueries.addBooking(x,a,b,currentTimestamp);
           // if(result5 == 1)
           //     JOptionPane.showMessageDialog(this,"Customer moved from Waitlist","Customer Booked!", JOptionPane.PLAIN_MESSAGE);   
        }    
        else
            JOptionPane.showMessageDialog(this, "Booking not Removed","Error", JOptionPane.PLAIN_MESSAGE);
        
        
        CustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(results1.toArray()));
        CustomerCancelCombo.setModel(new javax.swing.DefaultComboBoxModel(results1.toArray()));
        CustomerInfoCombo.setModel(new javax.swing.DefaultComboBoxModel(results1.toArray()));
    }//GEN-LAST:event_CancelBookingButtonActionPerformed

    private void AddDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDayButtonActionPerformed
        // TODO add your handling code here:
        //String y = AddDayField.getText();
        day = new Day();
        java.sql.Date y = java.sql.Date.valueOf(AddDayField.getText());
        
        int result10 = day.addDay(y);
        if(result10 == 1)
            JOptionPane.showMessageDialog(this,"Day Added!","Day Added", JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Day not Added","Error", JOptionPane.PLAIN_MESSAGE);
        results1 = customer.getAllCustomers();
        results3 = day.getAllDays();
        DayComboBox.setModel(new javax.swing.DefaultComboBoxModel(results3.toArray()));
        DayStatusCombo.setModel(new javax.swing.DefaultComboBoxModel(results3.toArray()));
    }//GEN-LAST:event_AddDayButtonActionPerformed
//This is where to add what to dipslay when choose customer
    private void CustomerInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerInfoButtonActionPerformed
        // TODO add your handling code here:
        BookingFlightStatusTF.setText("");
        BookingDayStatusTF.setText("");
        WaitlistFlightStatusTF.setText("");
        WaitlistDayStatusTF.setText("");
        
        String x = CustomerInfoCombo.getSelectedItem().toString();
        
        fNameCInfo = bookingsQueries.getBookingFlight(x);
        dayCInfo = bookingsQueries.getBookingDate(x);
        String z = fNameCInfo.get(0);
        Date d = dayCInfo.get(0);
        //TestCombo.setModel(new javax.swing.DefaultComboBoxModel(fNameCInfo.toArray()));
        BookingFlightStatusTF.setText("" + z);
        BookingDayStatusTF.setText("" + d);
        
        fNameCInfoW = waitlistQueries.getBookingFlight(x);
        dayCInfoW = waitlistQueries.getBookingDate(x);
        String z1 = fNameCInfoW.get(0);
        Date d1 = dayCInfoW.get(0);
        TestCombo.setModel(new javax.swing.DefaultComboBoxModel(fNameCInfoW.toArray()));
        WaitlistFlightStatusTF.setText("" + z1);
        WaitlistDayStatusTF.setText("" + d1);
    }//GEN-LAST:event_CustomerInfoButtonActionPerformed

    private void FlightRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightRemoveButtonActionPerformed
        // TODO add your handling code here:
        String x = FlightRemoveCombo.getSelectedItem().toString();
        int result14 = flight.cancelFlight(x);
        if(result14 == 1)
            JOptionPane.showMessageDialog(this,"Flight removed!","Flight Removed", JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Flight not Removed","Error", JOptionPane.PLAIN_MESSAGE);

        FlightStatusCombo.setModel(new javax.swing.DefaultComboBoxModel(results2.toArray()));
        FlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(results2.toArray()));
        FlightRemoveCombo.setModel(new javax.swing.DefaultComboBoxModel(results2.toArray()));
    }//GEN-LAST:event_FlightRemoveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomerButton;
    private javax.swing.JButton AddDayButton;
    private javax.swing.JTextField AddDayField;
    private javax.swing.JTextField AddFlightField;
    private javax.swing.JButton AddSeatButton;
    private javax.swing.JButton BookButton;
    private javax.swing.JTextField BookingDayStatusTF;
    private javax.swing.JTextField BookingFlightStatusTF;
    private javax.swing.JButton CancelBookingButton;
    private javax.swing.JComboBox<String> CustomerCancelCombo;
    private javax.swing.JComboBox<String> CustomerComboBox;
    private javax.swing.JButton CustomerInfoButton;
    private javax.swing.JComboBox<String> CustomerInfoCombo;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JTextField CustomerNameTextField;
    private javax.swing.JComboBox<String> CustomersListComboBox;
    private javax.swing.JComboBox<String> DayComboBox;
    private javax.swing.JComboBox<String> DayStatusCombo;
    private javax.swing.JComboBox<String> FlightComboBox;
    private javax.swing.JButton FlightRemoveButton;
    private javax.swing.JComboBox<String> FlightRemoveCombo;
    private javax.swing.JButton FlightStatusButton;
    private javax.swing.JComboBox<String> FlightStatusCombo;
    private javax.swing.JSpinner SeatSpinner;
    private javax.swing.JComboBox<String> TestCombo;
    private javax.swing.JButton ViewWaitlistButton;
    private javax.swing.JComboBox<String> WaitlistDayCombo;
    private javax.swing.JTextField WaitlistDayStatusTF;
    private javax.swing.JTextField WaitlistFlightStatusTF;
    private javax.swing.JComboBox<String> WaitlistStatusBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
